sudo: false
language: java
install:
  - git clone https://github.com/chopshop-166/wpilib-mirror.git ~/wpilib
  - pip install --user flake8
script:
  - ant jar
  - cd Vision && flake8 vision2016.py
jdk: oraclejdk8
